<?php

namespace App\Console\Commands;

use App\Models\Siswa;
use App\Support\RfidUid;
use Illuminate\Console\Command;

class ClearAutoGeneratedStudentRfid extends Command
{
    protected $signature = 'siswa:clear-auto-rfid
                            {--dry-run : Show how many RFID would be cleared without writing}
                            {--force : Skip confirmation prompt}';

    protected $description = 'Clear legacy auto-generated siswa RFID (S{sekolah}{NIS}, short or long NIS) so cards must be scanned manually';

    public function handle(): int
    {
        $candidates = Siswa::query()
            ->with('rfid')
            ->whereHas('rfid')
            ->orderBy('id')
            ->get(['id', 'nis', 'name', 'sekolah_id']);

        $matches = $candidates->filter(function (Siswa $siswa) {
            return RfidUid::isAutoGenerated(
                $siswa->rfidUid(),
                (string) $siswa->nis,
                $siswa->sekolah_id !== null ? (int) $siswa->sekolah_id : null
            );
        });

        $count = $matches->count();

        if ($count === 0) {
            $this->info('Tidak ada RFID otomatis yang perlu dibersihkan.');

            return self::SUCCESS;
        }

        $this->warn("Ditemukan {$count} siswa dengan RFID otomatis (pola S + sekolah + NIS).");

        if ($this->option('dry-run')) {
            $this->table(
                ['ID', 'NIS', 'Nama', 'RFID'],
                $matches->take(25)->map(fn (Siswa $s) => [$s->id, $s->nis, $s->name, $s->rfidUid()])->all()
            );
            if ($count > 25) {
                $this->line('… dan '.($count - 25).' lainnya.');
            }
            $this->info('Dry-run saja — tidak ada perubahan. Jalankan tanpa --dry-run untuk membersihkan.');

            return self::SUCCESS;
        }

        if (! $this->option('force') && ! $this->confirm("Kosongkan RFID untuk {$count} siswa?", true)) {
            $this->info('Dibatalkan.');

            return self::SUCCESS;
        }

        $updated = 0;
        foreach ($matches as $siswa) {
            $siswa->assignRfid(null);
            $updated++;
        }

        $this->info("Berhasil mengosongkan RFID pada {$updated} siswa. Scan kartu fisik saat edit siswa / Kontrol RFID.");

        return self::SUCCESS;
    }
}
