<?php

namespace App\Support;

use App\Models\Rfid;
use Illuminate\Validation\Rule;

final class RfidUid
{
    /**
     * Historical auto-generated UID format: S{sekolah_id:02d}{nis padded to 10 when shorter}.
     * Longer NIS were stored as S{sekolah}{full NIS} (PHP str_pad does not truncate).
     * Kept for detecting/cleaning legacy values — new records must use physical card UIDs.
     */
    public static function fromNis(string $nis, int $sekolahId): string
    {
        $normalized = VirtualAccountNumber::normalizeNis($nis) ?? '';

        return sprintf('S%02d%s', $sekolahId, self::legacyNisSuffix($normalized));
    }

    public static function isAutoGenerated(?string $rfidUid, ?string $nis, ?int $sekolahId = null): bool
    {
        $uid = self::sanitize($rfidUid);
        $normalized = VirtualAccountNumber::normalizeNis($nis);

        if ($uid === null || $normalized === null) {
            return false;
        }

        foreach (self::legacyCandidates($normalized, $sekolahId) as $candidate) {
            if ($uid === $candidate) {
                return true;
            }
        }

        // S{any 2-digit school}{NIS} — matches even if siswa.sekolah_id changed later.
        if (preg_match('/^S\d{2}(\d+)$/', $uid, $matches) !== 1) {
            return false;
        }

        $suffix = $matches[1];

        return $suffix === $normalized
            || $suffix === self::legacyNisSuffix($normalized);
    }

    /**
     * @return list<string>
     */
    private static function legacyCandidates(string $normalizedNis, ?int $sekolahId): array
    {
        $suffixes = array_values(array_unique([
            $normalizedNis,
            self::legacyNisSuffix($normalizedNis),
        ]));

        $candidates = [];

        if ($sekolahId !== null && $sekolahId >= 1) {
            foreach ($suffixes as $suffix) {
                $candidates[] = sprintf('S%02d%s', $sekolahId, $suffix);
                $candidates[] = sprintf('S%d%s', $sekolahId, $suffix);
            }
        }

        return array_values(array_unique($candidates));
    }

    /** Pad short NIS to 10 digits; leave longer NIS unchanged (historical seeder/import). */
    private static function legacyNisSuffix(string $normalizedNis): string
    {
        return strlen($normalizedNis) < 10
            ? str_pad($normalizedNis, 10, '0', STR_PAD_LEFT)
            : $normalizedNis;
    }

    public static function sanitize(mixed $value): ?string
    {
        if ($value === null) {
            return null;
        }

        // Strip scanner CR/LF/control chars from keyboard-wedge / paste input.
        $uid = preg_replace('/[\x00-\x1F\x7F]/', '', trim((string) $value)) ?? '';

        return $uid === '' ? null : $uid;
    }

    /**
     * @return array<int, mixed>
     */
    public static function rules(?int $ignoreSiswaId = null, bool $required = false): array
    {
        $rfidId = $ignoreSiswaId === null
            ? null
            : Rfid::query()->where('siswa_id', $ignoreSiswaId)->value('id');

        return [
            $required ? 'required' : 'nullable',
            'string',
            'max:64',
            'regex:/^[A-Za-z0-9_-]+$/',
            Rule::unique('rfid', 'uid')->ignore($rfidId),
        ];
    }

    /**
     * @return array<string, string>
     */
    public static function messages(): array
    {
        return [
            'rfid_uid.required' => 'RFID wajib diisi.',
            'rfid_uid.unique' => 'RFID sudah digunakan.',
            'rfid_uid.regex' => 'RFID hanya boleh berisi huruf, angka, strip, dan garis bawah.',
        ];
    }

    /**
     * @return array<int, mixed>
     */
    public static function guruRules(?int $ignoreGuruId = null): array
    {
        $rfidId = $ignoreGuruId === null
            ? null
            : Rfid::query()->where('guru_id', $ignoreGuruId)->value('id');

        return [
            'nullable',
            'string',
            'max:64',
            'regex:/^[A-Za-z0-9_-]+$/',
            Rule::unique('rfid', 'uid')->ignore($rfidId),
        ];
    }

    /**
     * @return array<string, string>
     */
    public static function guruMessages(): array
    {
        return [
            'rfid_uid.unique' => 'RFID sudah digunakan.',
            'rfid_uid.regex' => 'RFID hanya boleh berisi huruf, angka, strip, dan garis bawah.',
        ];
    }
}
