<?php

use App\Support\RfidUid;

test('sanitizes scanner paste control characters from rfid', function () {
    expect(RfidUid::sanitize("ABC123\r\n"))->toBe('ABC123')
        ->and(RfidUid::sanitize("  UID-01\t"))->toBe('UID-01')
        ->and(RfidUid::sanitize(''))->toBeNull()
        ->and(RfidUid::sanitize(null))->toBeNull();
});

test('detects legacy auto-generated rfid from nis', function () {
    expect(RfidUid::fromNis('12345', 1))->toBe('S010000012345')
        ->and(RfidUid::isAutoGenerated('S010000012345', '12345', 1))->toBeTrue()
        ->and(RfidUid::isAutoGenerated('PHYSICARD01', '12345', 1))->toBeFalse()
        ->and(RfidUid::isAutoGenerated('S010000012345', '99999', 1))->toBeFalse();
});

test('detects long-nis auto-generated rfid pattern', function () {
    $nis = '512336041084200004';

    expect(RfidUid::fromNis($nis, 1))->toBe('S01512336041084200004')
        ->and(RfidUid::isAutoGenerated('S01512336041084200004', $nis, 1))->toBeTrue()
        // Still auto even if sekolah_id later changed / unknown
        ->and(RfidUid::isAutoGenerated('S01512336041084200004', $nis, 3))->toBeTrue()
        ->and(RfidUid::isAutoGenerated('S01512336041084200004', $nis, null))->toBeTrue()
        ->and(RfidUid::isAutoGenerated('S02512336041084200004', $nis, null))->toBeTrue()
        ->and(RfidUid::isAutoGenerated('CARD01512336041084200004', $nis, 1))->toBeFalse();
});

test('detects unpadded single-digit school prefix variant', function () {
    expect(RfidUid::isAutoGenerated('S112345', '12345', 1))->toBeTrue();
});
